### ISSUE TITLE
About the parsing the change history of the apps.

### ISSUE THREAD

**Issue by ShangwenWang** [USI-INF-Software/ICSE21-ReplicationPackage-Fears#2]
Dear authors, 
Thanks for sharing the great work.
After reading the paper, I'm quite interested with the analysis procedure of the apps' change histories. However, I only get the app list you used in this study currently. I wonder if you are going to share the related code.

Many thanks

**Comment by Em11FW** [comment]
Hi Shangwen Wang, 
For the source code of parsing the apps' history, please refer to [https://github.com/Em11FW/FeaRS](url).
Cheers.
